### ISSUE TITLE
text (link,....) no space and it long -> breaking UI

### ISSUE THREAD

**Issue by cutbypham** [OngDev/youtube-livechat#10]
![image](https://user-images.githubusercontent.com/40050527/115890411-1bd9ea00-a47f-11eb-8012-26346056834d.png)

**Comment by thuanpham2311** [comment]
Fixed: commit 09eb881

**Comment by cutbypham** [comment]
35362fb66e08d3c65ce99da6b6fd8e72c1b3c5e5
